Added-eye-icon-button-on-registration-Page
annu12340/CS50-Final-Project pull request #10
Opened 2020-10-01 13:07 UTC by arbazkhan56

I am adding an icon on the registration page. I hope you Like it. And your design is very good looking. I Like it.

2020-10-02 06:03 UTC, annu12340 commented
Hey thanks for the pr
I liked that icon 😄

2020-10-02 06:04 UTC, annu12340 requested changes

2020-10-02 06:04 UTC, annu12340 commented on templates/register.html
> +    	.icon-wrapper{
Add the css inside **static** folder

2020-10-02 06:09 UTC, annu12340 requested changes

2020-10-02 06:09 UTC, annu12340 commented on templates/register.html
> +    	function myFunction() {
And change the function name from **myFunction()** to something very specific and relevant

2020-10-02 17:47 UTC, arbazkhan56 commented
> Hey thanks for the pr
> I liked that icon 😄

Thank you. I am changing it according to you.

2020-10-03 07:25 UTC, annu12340 commented
Pls resolve the conflicts

2020-10-04 03:31 UTC, merged